Личный проект: обратная сторона реальности
htmlacademy-react/1047897-what-to-watch-5 pull request #6
Opened 2020-10-13 17:00 UTC by RomanDovgii

Возникли следующие вопросы:

1. В некоторых случаях при использовании history пишется, что он не определен, хотя функция идет из app.
2. Возникла проблема с валидацией props в catalog - там есть опциональная часть, которая может быть не всегда заполнена. Не отмечал ее как обязательную, но стреляет ошибка:
` The prop `isRequired` is marked as required in `Catalog`, but its value is `undefined``
3. Немного не понимаю как здесь должна быть устроена навигация и что на что должно вести - привело в ступор в некоторых моментах с линкованием страниц между друг другом. Что у нас должно вести на my list в данный момент?

---
:mortar_board: [Личный проект: обратная сторона реальности](https://up.htmlacademy.ru/react/5/user/1047897/tasks/9)

2020-10-14 12:17 UTC, balesniy requested changes
>     1. В некоторых случаях при использовании history пишется, что он не определен, хотя функция идет из app.

мне не удалось повторить ошибку, опиши кейс пожалуйста

>     2. Возникла проблема с валидацией props в catalog - там есть опциональная часть, которая может быть не всегда заполнена. 

отметил в коде

>     3. Немного не понимаю как здесь должна быть устроена навигация и что на что должно вести - привело в ступор в некоторых моментах с линкованием страниц между друг другом. Что у нас должно вести на my list в данный момент?

судя по ТЗ - "Клик по аватарке пользователя выполняет переход на страницу MyList (/mylist)."

2020-10-14 12:17 UTC, balesniy commented on src/components/movie-page/movie-page.jsx
> +  const {movies} = props;
семантичнее будет передавать отдельно фильм и список похожих

2020-10-14 12:17 UTC, balesniy commented on src/components/my-list-page/my-list-page.jsx
> +  const filteredMovies = movies.filter((movie) => movie.isMyList);
подготовку списка лучше вынести из компонента, чтобы при каждом рендере их не перебирать

2020-10-14 12:17 UTC, balesniy commented on src/components/player-page/modules/player-exit.jsx
> +      <button
кнопку в Link лучше не заворачивать, тут или push или просто Link

2020-10-14 12:17 UTC, balesniy commented on src/components/types/types.js
> +  onMouseEnter: PropTypes.func.isRequired
выглядит избыточно для одной функции

2020-10-14 12:17 UTC, balesniy commented on src/components/types/types.js
> +  movies: PropTypes.arrayOf(PropTypes.shape(movieType).isRequired).isRequired
movieType уже shape, лишняя обертка

2020-10-14 12:17 UTC, balesniy commented on src/components/types/types.js
> +const OptionalListType = PropTypes.arrayOf(optionalListItemType);
лишняя заглавная

2020-10-14 12:17 UTC, balesniy commented on src/utils/const.js
> +export const MINIMUM_STARRING = 5;
https://up.htmlacademy.ru/react/5/criteries#d4

2020-10-14 12:17 UTC, balesniy commented on src/utils/utils.js
> +  const starring = [];
https://up.htmlacademy.ru/react/5/criteries#b9

2020-10-14 12:17 UTC, balesniy commented on src/utils/utils.js
> +    text = text + getRandomElementFromArray(sentences) + `. `;
похоже на join

2020-10-14 12:17 UTC, balesniy commented on src/utils/utils.js
> +    movies.push(movie);
похоже на map

2020-10-15 13:12 UTC, RomanDovgii commented on src/utils/utils.js
> +    movies.push(movie);
Извиняюсь, но map же вроде метод массива, который тут не получится использовать, так как тут нет массива, к которому можно применить map. Разве нет?

2020-10-15 13:37 UTC, RomanDovgii commented on src/components/catalog/modules/genres-list.jsx
> +  if (genres) {
Он как раз является опциональным, так как не всегда требуется для отрисовки каталога

2020-10-15 14:01 UTC, balesniy commented on src/utils/utils.js
> +    movies.push(movie);
помнишь как на js2 генерировали моки?

2020-10-15 14:01 UTC, balesniy commented on src/components/catalog/modules/genres-list.jsx
> +  if (genres) {
тогда нужно убрать isRequired

2020-10-15 15:31 UTC, RomanDovgii commented on src/utils/utils.js
> +    movies.push(movie);
Понял о чем ты, просто раньше не использовал этот метод, спасибо, что тыкнул куда нужно посмотреть!

2020-10-15 15:35 UTC, RomanDovgii commented on src/components/catalog/modules/genres-list.jsx
> +  if (genres) {
За него как раз отвечал optionalArray, который сейчас переделал.

2020-10-15 15:42 UTC, RomanDovgii commented on src/components/player-page/modules/player-exit.jsx
> +      <button
То есть заменить button на link? Либо добавит onClick для button?

2020-10-15 15:43 UTC, RomanDovgii commented on src/components/types/types.js
> +  onMouseEnter: PropTypes.func.isRequired
А если в компонент будет передаваться несколько функций для кликов на разные кнопки?

2020-10-15 15:46 UTC, balesniy commented on src/components/types/types.js
> +  onMouseEnter: PropTypes.func.isRequired
тогда это уже не onMouseEnterType

2020-10-15 16:23 UTC, RomanDovgii commented on src/components/movie-page/movie-page.jsx
> +  const {movies} = props;
Я так понимаю, что в дургих компонентах также следует их на данный момент разделить, так как GBH в данный момент является продвигаемым фильмом. Так?

2020-10-15 16:26 UTC, balesniy commented on src/components/movie-page/movie-page.jsx
> +  const {movies} = props;
у нас с сервера отдельными запросами придут промо и основной список

2020-10-15 16:32 UTC, RomanDovgii commented on src/components/add-review-page/modules/add-review.jsx
> +              <input className="rating__input" id="star-1" type="radio" name="rating" value="1" onChange={this._handleChange}/>
Можно поподробнее о том как явно указать checked?

2020-10-15 16:33 UTC, RomanDovgii commented on src/components/add-review-page/modules/add-review.jsx
> +              onChange={this._handleChange}
Об этом тоже, если возможно поподробнее, как делаются подобные моменты?

2020-10-15 17:04 UTC, RomanDovgii commented
По поводу проблемы с history.push. 
Если я его пробрасываю в любой компонент кроме mainPage - возникает проблема с тем, что получается ошибка "history.push is not a function", при этом метод проброса одинаков с mainPage и ничем не отличается.

2020-10-15 17:29 UTC, RomanDovgii commented on src/components/movie-page/movie-page.jsx
> +  const {movies} = props;
Понял, спасибо, тогда так и сделаю.

2020-10-15 17:30 UTC, RomanDovgii commented on src/components/player-page/modules/player-exit.jsx
> +      <button
Хорошо, но как раз при использовании кнопки возникает та самая проблема с history, написал о ней в Skype подробнее.

2020-10-15 19:39 UTC, RomanDovgii commented
Вроде теперь все верно, вопрос по использованию индекса без использования currentElement в .map так и остался висеть. 
И можно поподробнее по поводу управляемого элемента?

2020-10-15 20:38 UTC, balesniy commented on src/components/add-review-page/modules/add-review.jsx
> +              onChange={this._handleChange}
https://ru.reactjs.org/docs/forms.html#the-textarea-tag

2020-10-15 20:40 UTC, balesniy commented on src/components/add-review-page/modules/add-review.jsx
> +              <input className="rating__input" id="star-1" type="radio" name="rating" value="1" onChange={this._handleChange}/>
https://ru.reactjs.org/docs/forms.html#handling-multiple-inputs

2020-10-15 20:43 UTC, balesniy commented
> И можно поподробнее по поводу управляемого элемента?

https://ru.reactjs.org/docs/forms.html#controlled-components

2020-10-16 08:43 UTC, balesniy commented on src/components/movie-page/movie-page.jsx
> +          movies = {movies}
со страницы фильма можно прокинуть в список уже готовые похожие фильмы, подходящие по жанру

2020-10-16 08:43 UTC, merged