Module4 task2
htmlacademy-react/1047897-what-to-watch-5 pull request #8
Opened 2020-10-22 11:14 UTC by RomanDovgii

2020-10-22 19:41 UTC, balesniy requested changes

2020-10-22 19:41 UTC, balesniy commented on src/components/movie-page/modules/movie-card.jsx
> +                  <li className={`movie-nav__item ${this.state.shownScreen === MovieScreenTab.OVERVIEW ? `movie-nav__item--active` : ``}`}>
список табов просится в цикл

2020-10-22 19:41 UTC, balesniy commented on src/components/small-movie-card/small-movie-card.jsx
> -  componentWillUnmount() {
componentWillUnmount нам пригодится чтобы выключить таймер при клике на карточку

2020-10-22 19:41 UTC, balesniy commented on src/components/tabs/tabs.jsx
> +import {comments} from "../../mocks/comments";
все данные компонент должен получить через пропс

2020-10-22 19:41 UTC, balesniy commented on src/components/tabs/tabs.jsx
> +        <React.Fragment>
отдельные табы хочется в отдельные компоненты оформить

2020-10-22 19:41 UTC, balesniy commented on src/components/video-player/video-player.jsx
>  export default class VideoPlayer extends PureComponent {
чтобы переиспользовать этот компонент для страницы плеера, придется много логики добавить, возможно проще отдельный компонент завести

2020-10-22 19:41 UTC, balesniy commented on src/mocks/comments.js
> +  accumulator.push(movie.id);
это map

2020-10-22 19:41 UTC, balesniy commented on src/utils/const.js
>    isMyList: false
моки лучше сразу из констант убрать, или потом не забыть почистить

2020-10-22 19:41 UTC, balesniy commented on src/utils/utils.js
> +  let comments = {};
const

2020-10-22 19:41 UTC, balesniy commented on src/utils/utils.js
> +  movieIds.map((id) => {
а тут reduce )

2020-10-23 06:12 UTC, RomanDovgii commented on src/utils/const.js
>    isMyList: false
Пусть лучше пока побудут, а потом уже удалим, когда подключим сеть

2020-10-23 06:16 UTC, RomanDovgii commented on src/components/tabs/tabs.jsx
> +import {comments} from "../../mocks/comments";
Кстати, а разве комментарии не будут прилетать отдельно?

2020-10-23 06:23 UTC, RomanDovgii commented on src/utils/utils.js
> +  movieIds.map((id) => {
*Злобное клацание клешнями от непонимания, почему тут reduce, а там map*

2020-10-23 07:33 UTC, RomanDovgii commented on src/components/video-player/video-player.jsx
>  export default class VideoPlayer extends PureComponent {
Давай его пока временно подержим в данном состоянии, а при работе с плеером - заведем отдельный компонент дабы не плодить логику?

2020-10-23 13:18 UTC, balesniy commented on src/components/tabs/tabs.jsx
> +import {comments} from "../../mocks/comments";
будут, но через пропс

2020-10-23 13:20 UTC, balesniy commented on src/utils/utils.js
> +  movieIds.map((id) => {
reduce нужен чтобы свернуть массив в значение, а map нужен для преобразования элементов массива. грубо говоря на выходе у редьюса будет что то одно, а у мапа будет столько же сколько и было

2020-10-23 13:27 UTC, balesniy approved these changes

2020-10-23 13:27 UTC, balesniy commented on src/components/small-movie-card/small-movie-card.jsx
> +  componentWillUnmount() {
https://up.htmlacademy.ru/react/5/criteries#d10

2020-10-23 13:27 UTC, balesniy commented on src/mocks/comments.js
> +
const movieIds = movies.map(({id}) => id);

2020-10-23 13:27 UTC, balesniy commented on src/utils/utils.js
> +export const generateActorsText = (actors) => {
на утилиту не похоже, jsx

2020-10-23 13:27 UTC, merged